# CMake generated Testfile for 
# Source directory: /home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples
# Build directory: /home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/stats/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-time-probe-example "ns3.36.1-time-probe-example-optimized")
set_tests_properties(ctest-time-probe-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;1;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-example "ns3.36.1-gnuplot-example-optimized")
set_tests_properties(ctest-gnuplot-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-double-probe-example "ns3.36.1-double-probe-example-optimized")
set_tests_properties(ctest-double-probe-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-aggregator-example "ns3.36.1-gnuplot-aggregator-example-optimized")
set_tests_properties(ctest-gnuplot-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-gnuplot-helper-example "ns3.36.1-gnuplot-helper-example-optimized")
set_tests_properties(ctest-gnuplot-helper-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-aggregator-example "ns3.36.1-file-aggregator-example-optimized")
set_tests_properties(ctest-file-aggregator-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
add_test(ctest-file-helper-example "ns3.36.1-file-helper-example-optimized")
set_tests_properties(ctest-file-helper-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/stats/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;20;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/stats/examples/CMakeLists.txt;0;")
