# CMake generated Testfile for 
# Source directory: /home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples
# Build directory: /home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/cmake-cache/src/wifi/examples
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(ctest-wifi-phy-test "ns3.36.1-wifi-phy-test-optimized")
set_tests_properties(ctest-wifi-phy-test PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;1;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-test-interference-helper "ns3.36.1-wifi-test-interference-helper-optimized")
set_tests_properties(ctest-wifi-test-interference-helper PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;11;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-manager-example "ns3.36.1-wifi-manager-example-optimized")
set_tests_properties(ctest-wifi-manager-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;21;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-trans-example "ns3.36.1-wifi-trans-example-optimized")
set_tests_properties(ctest-wifi-trans-example PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;33;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-phy-configuration "ns3.36.1-wifi-phy-configuration-optimized")
set_tests_properties(ctest-wifi-phy-configuration PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;45;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
add_test(ctest-wifi-bianchi "ns3.36.1-wifi-bianchi-optimized")
set_tests_properties(ctest-wifi-bianchi PROPERTIES  WORKING_DIRECTORY "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build/optimized/src/wifi/examples/" _BACKTRACE_TRIPLES "/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/macros-and-definitions.cmake;1337;add_test;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/build-support/custom-modules/ns3-module-macros.cmake;524;set_runtime_outputdirectory;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;52;build_lib_example;/home/lyj/lyjns3/ns3bbr/ns-allinone-3.36.1/ns-3.36.1/src/wifi/examples/CMakeLists.txt;0;")
